version: '3'
services:
  api:
    image: sample-express-app
    container_name: mobiledev_rest_api
    build: .
    networks:
      - backend
    ports:
      - "3003:3003"
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  web-cli:
    image: sample-express-app
    networks:
      - backend
    command: sh

networks:
  backend:
    driver: bridge
